### PR TITLE
fix(#169): Replace `installFetch()` with `installPolyfills()`

### PR DESCRIPTION
**Pull request by pham**
# Summary

Replace `src/files/shims.js` with the polyfills version.

Fixes: #169

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
Thanks

**Comment by eXodes** [comment]
@jthegedus Hi James, is this going to be merged anytime soon?

**Comment by koreypeters-dexcom** [comment]
Would love to see this merged as well.

**Comment by Nushio** [comment]
Hi Pham, 

I've tested your changes on my sveltekit project and it's working fine. I also went ahead and fixed the integration tests that are currently failing, but I'm not sure how to push the commit onto this PR. 
https://github.com/Nushio/svelte-adapter-firebase/commit/d356444c6c6e771138672766ccad7568cc7a5176

I'd like to release the latest version of svelte-adapter-firebase with my fixes on Windows, your polyfills change, and co3k's header's pr (with a minor fix) as version 0.15.0 this week, if there are no objections / issues.

**Comment by pham** [comment]
> Hi Pham,
> 
> I've tested your changes on my sveltekit project and it's working fine. I also went ahead and fixed the integration tests that are currently failing, but I'm not sure how to push the commit onto this PR. [Nushio@d356444](https://github.com/Nushio/svelte-adapter-firebase/commit/d356444c6c6e771138672766ccad7568cc7a5176)
> 
> I'd like to release the latest version of svelte-adapter-firebase with my fixes on Windows, your polyfills change, and co3k's header's pr (with a minor fix) as version 0.15.0 this week, if there are no objections / issues.

Nushio,
If you'd create a pull request on my [fork](https://github.com/pham/svelte-adapter-firebase) with your changes, I'll merge it and hopefully, that will get updated here.

**Comment by Nushio** [comment]
Done! 
https://github.com/pham/svelte-adapter-firebase/pull/2

**Review by Nushio — APPROVED** [review]
Looks good to me.

**Pull request merged**
