### PR TITLE
chore!: Sync with kit@1.1.1 based on (PR #194 & #200)

### PR DESCRIPTION
**Pull request by pham**
# Summary

- Fix missing 2nd arg for `Server.respond()` causing `TypeError` (see error dump below)
- Add prerendered files to public dir (thanks @AndrewLester)
- Add Node.js 18 support

Fixes: #194 #200 

## TypeError
```
⚠  functions: TypeError: Cannot read properties of undefined (reading 'prerendering')
    at respond (/tmp/svelte-adapter-firebase-wxGf/functions/sveltekit/index.js:31409:14)
    at Server.respond (/tmp/svelte-adapter-firebase-wxGf/functions/sveltekit/index.js:31705:12)
    at svelteKit (/tmp/svelte-adapter-firebase-wxGf/functions/sveltekit/index.js:31767:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runFunction (/tmp/svelte-adapter-firebase-wxGf/node_modules/firebase-
```

### CODE REVIEW

**Comment by pham** [comment]
I ripped out the Node.js 18 check stuff from the merge (I didn't realize @jthegedus already removed them).

**Comment by pham** [comment]
Updated end-to-end test.

**Comment by jthegedus** [comment]
@pham You're a legend. You have come and saved me from the impending doom of updating this repo 🙏

**Review by jthegedus — APPROVED** [review]
Thanks so much @pham

**Comment by jthegedus** [comment]
I thought the `!` would mean release-please would identify this as a breaking change and include in it's Release. Annoying!

**Pull request merged**
