### PR TITLE
fix(#180): Prepend `Server.init` before calling `Server.respond`

### PR DESCRIPTION
**Pull request by pham**
# Summary

`hooks.js` initialization has been moved to `Server.init`. Add code to initialize hooks in `entry.js`.

Fixes: #180 

## Other Information

The test end-to-end test script and test config matrix were modified to accommodate the new SvelteKit layout system.

### CODE REVIEW

**Comment by Nushio** [comment]
I just finished migrating our massive project into the latest version of sveltekit (461 as of Sept 1). 
With your fix, it compiles and renders correctly. 

Thanks!

**Review by jthegedus — APPROVED** [review]
thanks for the update

**Comment by jthegedus** [comment]
@pham Are you able to look at https://github.com/jthegedus/svelte-adapter-firebase/runs/8147877651?check_suite_focus=true

I am afk for the next few days, but could merge a PR if raised.

**Comment by Nushio** [comment]
I think the issue is with 
> Cross-site POST form submissions are forbidden

I'll check it out today if @pahm doesn't get to it first

**Comment by pham** [comment]
@Nushio not able to get to this until next Monday. If you do a PR, I'll merge it. Thanks

**Comment by Nushio** [comment]
I'll send a PR tomorrow. I apologize for the delay but today we pushed to prod our big svelte site, using Svelte kit 471 and svelte adapter firebase 0.14.3! 

The svelte migration from 405 to the latest API was a bit scary at 145 files changed but requiered very little manual labor/review.

I also want to send a PR to "fix the docs" with the latest recommendations.

If anyone has any suggestions or questions, please let me know and I'll try to tackle them. :-)

**Comment by Nushio** [comment]
Minor update on this. The E2E test found a legit bug, which might be critical.
I fixed the E2E test but not the bug.
Basically, the E2E test is reporting a Cross Site Scripting bug as I reported. 

Running the sveltekit todo application through vite preview, the test runs fine (Testing post also works fine with vite dev). 
Running it through the firebase emulator, it returns the XSS error.

Found this issue regarding the adapter-node, which might be related.
https://github.com/sveltejs/kit/issues/6589

I checked my sveltekit apps, but my apps aren't affected by this because I'm not using the sveltekit page+server actions, and instead I make post requests to firebase cloud functions.

I'm still investigating how to fix this but I figured it was worth raising the attention. 
I'll create an issue if I cant figure this out.

**Comment by Nushio** [comment]
To add to this, when running the sveltekit todo app on the firebase emulator, attempting to send a todo fails, even through the browser.

**Comment by Nushio** [comment]
Figured it out. Someone smarter than me wouldn't have taken a bit over 3 hours but I learned a bit more about firebase and sveltekit.

**Pull request merged**
